# NumPy for Data Science - Complete Tutorial
This tutorial covers everything you need to know about NumPy, from the basics to advanced topics, including real-world applications.

## Table of Contents
1. [Introduction to NumPy](#1)
2. [Installing NumPy](#2)
3. [Creating Arrays](#3)
4. [Indexing & Slicing](#4)
5. [Array Manipulation](#5)
6. [Mathematical & Statistical Operations](#6)
7. [Broadcasting](#7)
8. [Random Number Generation](#8)
9. [Linear Algebra](#9)
10. [Working with Real Datasets](#10)

## 1.📌 Introduction to NumPy (Numerical Python) <a id='1'></a>
NumPy is a powerful library for numerical computing. It is the foundation of libraries such as Pandas, SciPy, TensorFlow, and Scikit-Learn.

**Why use NumPy?**
- Faster than Python lists
- Supports vectorized operations
- Used in machine learning and deep learning

## 2.📌 Installing NumPy <a id='2'></a>
To install NumPy, run:
```bash
pip install numpy
```

In [7]:
import numpy as np
print(np.__version__)  # Check installed version

1.24.3


##  3. 📌 Creating NumPy Arrays <a id='3'></a>

In [2]:
# 1D Array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1, arr1.shape)

# 2D Array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2, arr2.shape)

# 3D Array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3, arr3.shape)

[1 2 3 4 5] (5,)
[[1 2 3]
 [4 5 6]] (2, 3)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2)


# 4. 📌 Special Arrays

In [6]:

print(np.zeros((3, 3)))  # 3x3 matrix of zeros
print(np.ones((2, 4)))   # 2x4 matrix of ones
print(np.eye(4))         # 4x4 identity matrix
print(np.full((2, 3), 7))  # Matrix filled with a number
print(np.arange(1, 10, 2))  # [1 3 5 7 9] (start, stop, step)
print(np.linspace(0, 1, 5))  # 5 numbers between 0 and 1


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]


##  5.📌 Array Indexing & Slicing <a id='4'></a>

1️⃣ indexing

In [21]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  # First element
print(arr[-1]) # Last element


10
50


2️⃣ slicing

In [23]:
print(arr[1:4])  # Elements from index 1 to 3
print(arr[:3])   # First 3 elements
print(arr[-3:])  # Last 3 elements


[20 30 40]
[10 20 30]
[30 40 50]


## 6. 📌 Array Manipulation <a id='5'></a>

1️⃣ Reshaping 

In [18]:
arr = np.arange(1, 10)
arr2D = arr.reshape(3, 3)
print(arr2D)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


2️⃣ Stacking

In [19]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(np.vstack((a, b)))  # Vertical stack
print(np.hstack((a, b.T)))  # Horizontal stack


[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


3️⃣ Splitting Arrays

In [20]:
arr = np.arange(10)
print(np.split(arr, 2))  # Splits into 2 equal parts


[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


## 📌 7. Mathematical & Statistical Operations

1️⃣  Aggregate Functions

In [17]:
arr = np.array([10, 20, 30, 40])

print(arr.sum())       # Sum of elements
print(arr.mean())      # Mean
print(arr.std())       # Standard deviation
print(arr.min())       # Minimum
print(arr.max())       # Maximum


100
25.0
11.180339887498949
10
40


2️⃣  Basic Operations

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # Addition
print(a - b)   # Subtraction
print(a * b)   # Multiplication
print(a / b)   # Division
print(a ** 2)  # Squaring elements

100
25.0
11.180339887498949
10
40


## 📌 8. Broadcasting <a id='7'></a>

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr + 10)  # Adds 10 to each element


[[11 12 13]
 [14 15 16]]


## 📌 9. Random Number Generation <a id='8'></a>

In [15]:
print(np.random.rand(3, 3))  # Random numbers between 0-1
print(np.random.randn(3, 3))  # Random numbers between -1 and 1

print(np.random.randint(1, 100, (3, 3)))  # Random integers
print(np.random.normal(0, 1, (3, 3)))  # Normal distribution


[[0.55870502 0.46811052 0.8623984 ]
 [0.94622838 0.86989305 0.68385785]
 [0.38562569 0.83085789 0.54622024]]
[[-1.79071764  1.00690348 -1.43515554]
 [-0.4003504   0.46296999 -0.30646632]
 [ 0.32210733  1.19374953  0.82167838]]
[[66 98 13]
 [52 21 21]
 [78 83 52]]
[[ 0.15798652  0.34017785  0.49597355]
 [ 0.66387971  0.788463    1.34088198]
 [ 0.22893614  0.35061486 -1.55156888]]


## 📌 10. Linear Algebra With NumPy<a id='9'></a>

1️⃣ Matrix Multiplication

In [24]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B))  # Matrix multiplication


[[19 22]
 [43 50]]


2️⃣ Transpose & Inverse

In [26]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A.T)  # Transpose
print(np.linalg.inv(A))  # Inverse


[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


3️⃣ Determinant & Eigenvalues

In [27]:
print(np.linalg.det(A))  # Determinant
eigvals, eigvecs = np.linalg.eig(A)
print(eigvals)  # Eigenvalues
print(eigvecs)  # Eigenvectors


-2.0000000000000004
[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## 📌 11. Working with Real Datasets <a id='10'></a>

In [29]:
import pandas as pd

# Load CSV
# df = pd.read_csv('data.csv')
# print(df.head())